export const products = [
    {
      id: 1,
      marque: "Cetaphil",
      nom: "Cetaphil Sun SPF 50+",
      prix: "79.99 TND",
      discount: "99.99 TND",
      image: "/cardImgs/CeraveHydratant.jpeg",
      nouveaux: "Nouveau",
      rupture: "En stock",
      reduction: 10,
    },
    {
      id: 2,
      marque: "Vichy",
      nom: "Vichy Mineral 89 Serum",
      prix: "109.99 TND",
      discount: "129.99 TND",
      image: "/cardImgs/CetafilEcran.jpeg",
      nouveaux: "Nouveau",
      rupture: "En stock",
    },
    {
      id: 3,
      marque: "La Roche-Posay",
      nom: "Effaclar Duo+",
      prix: "89.99 TND",
      discount: "110.00 TND",
      image: "/cardImgs/ConcentréAnti-Imperfections.jpeg",
      nouveaux: "Best Seller",
      rupture: "En stock",
    },
    {
      id: 4,
      marque: "Bioderma",
      nom: "Bioderma Sensibio H2O",
      prix: "45.00 TND",
      discount: "60.00 TND",
      image: "/cardImgs/GelNettoyant.jpeg",
      nouveaux: "Top Vente",
      rupture: "En stock",
      reduction: 25
    },
    {
      id: 5,
      marque: "Avene",
      nom: "Avène Eau Thermale Spray",
      prix: "55.00 TND",
      discount: "70.00 TND",
      image: "/cardImgs/CrèmeRicheHydratation.jpeg",
      nouveaux: "Recommandé",
      rupture: "En stock",
    },
    {
      id: 6,
      marque: "Mustela",
      nom: "Mustela Gel Lavant Doux",
      prix: "39.99 TND",
      discount: "50.00 TND",
      image: "/cardImgs/HydranceLightHydrating.jpeg",
      nouveaux: "Nouveau",
      rupture: "En stock",
    },
  ];
  