export const products = [
    {
      id: 1,
      marque: "Cetaphil",
      nom: "Cetaphil Sun SPF 50+",
      prix: "79.99 TND",
      discount: "99.99 TND",
      image: "https://m.media-amazon.com/images/I/61Ubss1PryL._AC_SY879_.jpg",
      nouveaux: "Nouveau",
      rupture: "En stock",
    },
    {
      id: 2,
      marque: "Vichy",
      nom: "Vichy Mineral 89 Serum",
      prix: "109.99 TND",
      discount: "129.99 TND",
      image: "https://m.media-amazon.com/images/I/61NHYsYAGLL._AC_SY879_.jpg",
      nouveaux: "Nouveau",
      rupture: "En stock",
    },
    {
      id: 3,
      marque: "La Roche-Posay",
      nom: "Effaclar Duo+",
      prix: "89.99 TND",
      discount: "110.00 TND",
      image: "https://m.media-amazon.com/images/I/71bMpiKFFyL._AC_SY879_.jpg",
      nouveaux: "Best Seller",
      rupture: "En stock",
    },
    {
      id: 4,
      marque: "Bioderma",
      nom: "Bioderma Sensibio H2O",
      prix: "45.00 TND",
      discount: "60.00 TND",
      image: "https://m.media-amazon.com/images/I/81G7j34s1bL._AC_SY879_.jpg",
      nouveaux: "Top Vente",
      rupture: "En stock",
    },
    {
      id: 5,
      marque: "Avene",
      nom: "Avène Eau Thermale Spray",
      prix: "55.00 TND",
      discount: "70.00 TND",
      image: "https://m.media-amazon.com/images/I/61qmuZo4tWL._AC_SY879_.jpg",
      nouveaux: "Recommandé",
      rupture: "En stock",
    },
    {
      id: 6,
      marque: "Mustela",
      nom: "Mustela Gel Lavant Doux",
      prix: "39.99 TND",
      discount: "50.00 TND",
      image: "https://m.media-amazon.com/images/I/51oNwJkn1dL._AC_SY879_.jpg",
      nouveaux: "Nouveau",
      rupture: "En stock",
    },
  ];
  