export const products = [
  // Sions
  // Cetaphil
  {
    id: 1,
    marque: "Cetaphil",
    nom: "Cetaphil Sun SPF 50+",
    prix: "79.99 TND",
    discount: "99.99 TND",
    image: "/cardImgs/CetafilEcran.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    reduction: 20,
    Description:
      "Gel solaire léger avec aloe vera et vitamine E, protège contre les rayons UV et hydrate intensément.",
    category: "Beauté Soins",
    rating: 4.5,
    reviews: 120,
  },
  {
    id: 2,
    marque: "Cetaphil",
    nom: "Cetaphil Gentle Skin Cleanser",
    prix: "59.99 TND",
    discount: "75.00 TND",
    image: "/cardImgs/CetaphilOilSkinCleanser.jpeg",
    nouveaux: "Best Seller",
    rupture: "En stock",
    reduction: 20,
    Description:
      "Nettoyant doux pour le visage et le corps, adapté aux peaux sensibles.",
    category: "Beauté Soins",
    rating: 4.0,
    reviews: 80,
  },

  // Vichy
  {
    id: 3,
    marque: "Vichy",
    nom: "Vichy Mineral 89 Serum",
    prix: "109.99 TND",
    discount: "129.99 TND",
    image: "/cardImgs/VichyMineralSerum.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Booster quotidien avec acide hyaluronique pour une peau plus forte et hydratée.",

    category: "Beauté Soins",
    rating: 4.5,
    reviews: 65,
  },
  {
    id: 4,
    marque: "Vichy",
    nom: "Vichy Normaderm Phytosolution",
    prix: "89.99 TND",
    discount: "110.00 TND",
    image: "/cardImgs/VICHYNormadermPhytosolutionIntensivePurifyingGel.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description: "Soin correcteur pour peaux grasses à imperfections.",
    category: "Beauté Soins",
    rating: 4.0,
    reviews: 50,
  },

  // La Roche-Posay
  {
    id: 5,
    marque: "La Roche-Posay",
    nom: "Effaclar Duo+",
    prix: "89.99 TND",
    discount: "110.00 TND",
    image: "/cardImgs/EffaclarDuo.jpeg",
    nouveaux: "Best Seller",
    rupture: "En stock",
    Description:
      "Correcteur anti-imperfections qui réduit les marques et affine les pores.",
    category: "Beauté Soins",
    rating: 4.7,
    reviews: 90,
  },
  {
    id: 6,
    marque: "La Roche-Posay",
    nom: "La Roche-Posay Anthelios SPF 50+",
    prix: "99.99 TND",
    discount: "130.00 TND",
    image: "/cardImgs/AntheliosSPF50.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Crème solaire ultra-légère pour peaux sensibles, très haute protection UV.",
    category: "Beauté Soins",
    rating: 4.8,
    reviews: 75,
  },

  // Bioderma
  {
    id: 7,
    marque: "Bioderma",
    nom: "Bioderma Sensibio H2O",
    prix: "45.00 TND",
    discount: "60.00 TND",
    image: "/cardImgs/BiodermaSensibioH2O.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    reduction: 25,
    Description: "Eau micellaire démaquillante pour peaux sensibles.",
    category: "Beauté Soins",
    rating: 4.9,
    reviews: 30,
  },
  {
    id: 8,
    marque: "Bioderma",
    nom: "Bioderma Atoderm Crème",
    prix: "65.00 TND",
    discount: "85.00 TND",
    image: "/cardImgs/BiodermaAtoderm.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Crème ultra-nourrissante pour peaux très sèches ou atopiques.",
    category: "Beauté Soins",
    rating: 4.5,
    reviews: 40,
  },

  // Avene
  {
    id: 9,
    marque: "Avene",
    nom: "Avène Eau Thermale Spray",
    prix: "55.00 TND",
    discount: "70.00 TND",
    image: "/cardImgs/AvèneEauThermaleSpray.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description: "Spray d'eau thermale apaisante et anti-irritante.",
    category: "Beauté Soins",
    rating: 2.8, // bad review
    reviews: 12,
  },
  {
    id: 10,
    marque: "Avene",
    nom: "Avene Hydrance Aqua-Gel",
    prix: "79.00 TND",
    discount: "95.00 TND",
    image: "/cardImgs/AveneHydranceAqua-Gel.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Gel-crème hydratant 3-en-1 pour peaux sensibles déshydratées.",
    category: "Beauté Soins",
    rating: 4.2,
    reviews: 55,
  },

  // Mustela
  {
    id: 11,
    marque: "Mustela",
    nom: "Mustela Gel Lavant Doux",
    prix: "39.99 TND",
    discount: "50.00 TND",
    image: "/cardImgs/MustelaGelLavantDoux.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description: "Gel nettoyant doux pour bébé et enfant.",
    category: "Beauté Soins",
    rating: 4.3,
    reviews: 45,
  },
  {
    id: 12,
    marque: "Mustela",
    nom: "Mustela Hydra Bébé Crème Visage",
    prix: "49.99 TND",
    discount: "65.00 TND",
    image: "/cardImgs/MustelaHydraBébéCrèmeVisage.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Crème hydratante quotidienne pour la peau délicate des bébés.",
    category: "Beauté Soins",
    rating: 4.5,
    reviews: 40,
  },

  //  Eucerin
  {
    id: 13,
    marque: "Eucerin",
    nom: "Eucerin Hyaluron-Filler Day Cream",
    prix: "119.99 TND",
    discount: "145.00 TND",
    image: "/cardImgs/EucerinHyaluronFillerDayCream.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description: "Crème de jour anti-rides enrichie en acide hyaluronique.",
    category: "Beauté Soins",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 14,
    marque: "Eucerin",
    nom: "Eucerin pH5 Shower Oil",
    prix: "69.99 TND",
    discount: "85.00 TND",
    image: "/cardImgs/EucerinpH5ShowerOil.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description: "Huile de douche protectrice pour peaux sensibles.",
    category: "Beauté Soins",
    rating: 4.4,
    reviews: 50,
  },

  //  Nuxe
  {
    id: 15,
    marque: "Nuxe",
    nom: "Nuxe Huile Prodigieuse",
    prix: "99.99 TND",
    discount: "120.00 TND",
    image: "/cardImgs/NuxeHuileProdigieuse.jpeg",
    nouveaux: "Best Seller",
    rupture: "En stock",
    Description: "Huile sèche multifonctions visage, corps et cheveux.",
    category: "Beauté Soins",
    rating: 4.5,
    reviews: 80,
  },
  {
    id: 16,
    marque: "Nuxe",
    nom: "Nuxe Crème Fraîche de Beauté",
    prix: "89.00 TND",
    discount: "110.00 TND",
    image: "/cardImgs/NuxeCrèmeFraîchedeBeauté.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description: "Crème hydratante 48h pour peaux normales à mixtes.",
    category: "Beauté Soins",
    rating: 4.5,
    reviews: 60,
  },

  // Neutrogena
  {
    id: 17,
    marque: "Neutrogena",
    nom: "Neutrogena Hydro Boost Gel",
    prix: "65.00 TND",
    discount: "80.00 TND",
    image: "/cardImgs/NeutrogenaHydroBoostGel.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description: "Gel hydratant rafraîchissant avec acide hyaluronique.",
    category: "Beauté Soins",
    rating: 4.3,
    reviews: 50,
  },
  {
    id: 18,
    marque: "Neutrogena",
    nom: "Neutrogena Deep Clean Cleanser",
    prix: "45.00 TND",
    discount: "60.00 TND",
    image: "/cardImgs/NeutrogenaDeepCleanCleanser.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Nettoyant quotidien éliminant les impuretés et l'excès de sébum.",
    category: "Beauté Soins",
    rating: 4.0,
    reviews: 50,
  },

  //  The Ordinary
  {
    id: 19,
    marque: "The Ordinary",
    nom: "The Ordinary Niacinamide 10% + Zinc 1%",
    prix: "79.00 TND",
    discount: "95.00 TND",
    image: "/cardImgs/TheOrdinaryNiacinamied.jpeg",
    nouveaux: "Best Seller",
    rupture: "En stock",
    Description: "Sérum anti-imperfections et contrôle du sébum.",
    category: "Beauté Soins",
    rating: 4.5,
    reviews: 100,
  },
  {
    id: 20,
    marque: "The Ordinary",
    nom: "The Ordinary Hyaluronic Acid 2% + B5",
    prix: "85.00 TND",
    discount: "105.00 TND",
    image: "/cardImgs/TheOrdinaryHyaluronicAcid.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description: "Sérum hydratant intense pour toutes les peaux.",
    category: "Beauté Soins",
    rating: 4.5,
    reviews: 100,
  },

  //  CeraVe
  {
    id: 21,
    marque: "CeraVe",
    nom: "CeraVe Moisturizing Cream",
    prix: "99.99 TND",
    discount: "120.00 TND",
    image: "/cardImgs/CeraVe.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Crème hydratante riche en céramides pour restaurer la barrière cutanée.",
    category: "Beauté Soins",
    rating: 4.5,
    reviews: 100,
  },
  {
    id: 22,
    marque: "CeraVe",
    nom: "CeraVe Foaming Cleanser",
    prix: "55.00 TND",
    discount: "70.00 TND",
    image:
      "/cardImgs/CeraVe Foaming Cleanser for Normal to Oily Skin 473ml _ ASOS.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description: "Gel moussant nettoyant pour peaux normales à grasses.",
    category: "Beauté Soins",
    rating: 4.2,
    reviews: 60,
  },

  // Medicamment

  {
    id: 23,
    marque: "Panadol",
    nom: "Panadol Extra",
    prix: "12.00 TND",
    discount: "15.00 TND",
    image: "/cardImgs/PanadolExtra.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Analgésique et antipyrétique pour soulager douleurs et fièvre.",
    category: "Médicaments",
    rating: 4.2,
    reviews: 60,
  },
  {
    id: 24,
    marque: "Voltaren",
    nom: "Voltaren Emulgel",
    prix: "25.00 TND",
    discount: "30.00 TND",
    image: "/cardImgs/VoltarenEmulgel.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Gel anti-inflammatoire pour douleurs musculaires et articulaires.",
    category: "Médicaments",
    rating: 4.5,
    reviews: 80,
  },
  {
    id: 25,
    marque: "Dafalgan",
    nom: "Dafalgan 500mg",
    prix: "10.00 TND",
    discount: "12.00 TND",
    image: "/cardImgs/Dafalgan500mg.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description: "Traitement des douleurs modérées et fièvre légère.",
    category: "Médicaments",
    rating: 4.0,
    reviews: 50,
  },
  {
    id: 26,
    marque: "Nurofen",
    nom: "Nurofen 400mg",
    prix: "15.00 TND",
    discount: "18.00 TND",
    image: "/cardImgs/Nurofen400mg.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Soulagement des douleurs et inflammations légères à modérées.",
    category: "Médicaments",
    rating: 4.3,
    reviews: 50,
  },
  {
    id: 27,
    marque: "Advil",
    nom: "Advil 200mg",
    prix: "13.00 TND",
    discount: "16.00 TND",
    image: "/cardImgs/Advil200mg.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Soulagement rapide des douleurs légères à modérées et fièvre.",
    category: "Médicaments",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 28,
    marque: "Doliprane",
    nom: "Doliprane 1000mg",
    prix: "11.50 TND",
    discount: "14.00 TND",
    image: "/cardImgs/Doliprane1000mg.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Analgésique et antipyrétique pour douleurs fortes et fièvre élevée.",
    category: "Médicaments",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 29,
    marque: "Efferalgan",
    nom: "Efferalgan Vitamine C",
    prix: "14.00 TND",
    discount: "17.00 TND",
    image: "/cardImgs/EfferalganVitamineC.jpg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Soulagement des douleurs et renforcement du système immunitaire.",
    category: "Médicaments",
    rating: 2.5, // bad review
    reviews: 8,
  },
  {
    id: 30,
    marque: "Spasfon",
    nom: "Spasfon Lyoc",
    prix: "19.00 TND",
    discount: "22.00 TND",
    image: "/cardImgs/SpasfonLyoc.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Traitement des douleurs spasmodiques abdominales et urinaires.",
    category: "Médicaments",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 31,
    marque: "Gripex",
    nom: "Gripex Max",
    prix: "8.50 TND",
    discount: "10.00 TND",
    image: "/cardImgs/GripexMax.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description: "Traitement des symptômes du rhume et de la grippe.",
    category: "Médicaments",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 32,
    marque: "Thermacare",
    nom: "Thermacare Patch",
    prix: "18.00 TND",
    discount: "22.00 TND",
    image: "/cardImgs/ThermacarePatch.jpg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Patch chauffant pour soulager les douleurs musculaires et articulaires.",
    category: "Médicaments",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 33,
    marque: "Calmosine",
    nom: "Calmosine Enfants",
    prix: "15.00 TND",
    discount: "18.00 TND",
    image: "/cardImgs/CalmosineEnfants.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Infusion apaisante pour enfants contre les coliques et les douleurs abdominales.",
    category: "Médicaments",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 34,
    marque: "Mucosolvan",
    nom: "Mucosolvan 30mg",
    prix: "20.00 TND",
    discount: "25.00 TND",
    image: "/cardImgs/Mucosolvan30mg.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Traitement des affections des voies respiratoires supérieures.",
    category: "Médicaments",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 35,
    marque: "L52",
    nom: "L52",
    prix: "8.00 TND",
    discount: "10.00 TND",
    image: "/cardImgs/L52.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Traitement des troubles digestifs et des douleurs abdominales.",
    category: "Médicaments",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 36,
    marque: "Pansement",
    nom: "Pansement Compeed",
    prix: "5.00 TND",
    discount: "7.00 TND",
    image: "/cardImgs/PansementCompeed.png",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Pansement hydrocolloïde pour soulager et accélérer la guérison des ampoules.",
    category: "Produits de soin",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 37,
    marque: "Bion 3",
    nom: "Bion 3",
    prix: "30.00 TND",
    discount: "35.00 TND",
    image: "/cardImgs/Bion3.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Complément alimentaire pour renforcer les défenses immunitaires.",
    category: "Vitamines",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 38,
    marque: "Vicks",
    nom: "Vicks VapoRub",
    prix: "10.00 TND",
    discount: "12.00 TND",
    image: "/cardImgs/VicksVapoRub.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Baume apaisant pour soulager la toux et les douleurs musculaires.",
    category: "Produits de soin",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 39,
    marque: "Osteocare",
    nom: "Osteocare Plus",
    prix: "22.00 TND",
    discount: "26.00 TND",
    image: "/cardImgs/OsteocarePlus.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Complément alimentaire pour maintenir une bonne santé osseuse.",
    category: "Vitamines",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 40,
    marque: "Biogaran",
    nom: "Biogaran Vitamine D3",
    prix: "8.00 TND",
    discount: "10.00 TND",
    image: "/cardImgs/BiogaranVitamineD3.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Complément alimentaire pour renforcer les os et le système immunitaire.",
    category: "Vitamines",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 41,
    marque: "Inofolic",
    nom: "Inofolic",
    prix: "27.00 TND",
    discount: "30.00 TND",
    image: "/cardImgs/Inofolic.jpg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Complément alimentaire pour réguler le cycle menstruel et améliorer la fertilité.",
    category: "Produits de soin",
    rating: 4.0,
    reviews: 10,
  },

  //Compléments alimentaires
  {
    id: 42,
    marque: "Nutrilite",
    nom: "Nutrilite Double X",
    prix: "80.00 TND",
    discount: "90.00 TND",
    image: "/cardImgs/NutriliteDoubleX.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Complément alimentaire multivitaminé pour soutenir l'énergie et la vitalité.",
    category: "Compléments alimentaires",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 43,
    marque: "Orthomol",
    nom: "Orthomol Immun",
    prix: "55.00 TND",
    discount: "65.00 TND",
    image: "/cardImgs/OrthomolImmun.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Complément pour renforcer le système immunitaire, riche en vitamines et minéraux.",
    category: "Compléments alimentaires",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 44,
    marque: "Solgar",
    nom: "Solgar Omega 3",
    prix: "45.00 TND",
    discount: "50.00 TND",
    image: "/cardImgs/SolgarOmega3.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Complément alimentaire à base d'Oméga-3 pour favoriser la santé cardiovasculaire.",
    category: "Compléments alimentaires",
    rating: 2.9, // bad review
    reviews: 7,
  },
  {
    id: 45,
    marque: "Pharma Nord",
    nom: "Bio-Multi Vitamin",
    prix: "40.00 TND",
    discount: "48.00 TND",
    image: "/cardImgs/BiogaranVitamineD3.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Multivitamines et minéraux pour compléter l'alimentation quotidienne.",
    category: "Compléments alimentaires",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 46,
    marque: "Nature's Way",
    nom: "Nature's Way Vitamin C",
    prix: "25.00 TND",
    discount: "30.00 TND",
    image: "/cardImgs/Nature'sWayVitaminC.png",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Complément de vitamine C pour renforcer le système immunitaire et lutter contre la fatigue.",
    category: "Compléments alimentaires",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 47,
    marque: "Now Foods",
    nom: "Now Foods Calcium & Magnesium",
    prix: "18.00 TND",
    discount: "22.00 TND",
    image: "/cardImgs/NowFoodsCalcium&Magnesium.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Complément alimentaire pour maintenir des os solides et des muscles en bonne santé.",
    category: "Compléments alimentaires",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 48,
    marque: "Herbafit",
    nom: "Herbafit Probiotic",
    prix: "30.00 TND",
    discount: "35.00 TND",
    image: "/cardImgs/HerbafitProbiotic.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Probiotiques pour maintenir une flore intestinale saine et soutenir la digestion.",
    category: "Compléments alimentaires",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 49,
    marque: "Sundown Naturals",
    nom: "Sundown Naturals Biotin",
    prix: "12.00 TND",
    discount: "15.00 TND",
    image: "/cardImgs/SundownNaturalsBiotin.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Biotine pour favoriser la santé des cheveux, de la peau et des ongles.",
    category: "Compléments alimentaires",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 50,
    marque: "Garden of Life",
    nom: "Garden of Life Raw Organic Protein",
    prix: "65.00 TND",
    discount: "70.00 TND",
    image: "/cardImgs/GardenofLifeRawOrganicProtein.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Protéine végétale bio, idéale pour les sportifs et les végétariens.",
    category: "Compléments alimentaires",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 51,
    marque: "Biocyte",
    nom: "Biocyte Collagen Express",
    prix: "40.00 TND",
    discount: "45.00 TND",
    image: "/cardImgs/BiocyteCollagenExpress.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Complément alimentaire à base de collagène pour améliorer l'élasticité de la peau.",
    category: "Compléments alimentaires",
    rating: 4.3,
    reviews: 30,
  },

  //Bébé Maman

  {
    id: 52,
    marque: "Mustela",
    nom: "Mustela Crème Hydratante Bébé",
    prix: "20.00 TND",
    discount: "25.00 TND",
    image: "/cardImgs/MustelaCrèmeHydratanteBébé.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Crème hydratante pour la peau délicate des bébés, à base d'ingrédients naturels.",
    category: "Bébé Maman",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 53,
    marque: "Hipp",
    nom: "Hipp Baby Food - Porridge",
    prix: "15.00 TND",
    discount: "18.00 TND",
    image: "/cardImgs/HippBabyFood.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Porridge bio pour bébé, riche en vitamines et minéraux essentiels.",
    category: "Bébé Maman",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 54,
    marque: "Bepanthen",
    nom: "Bepanthen Pommade Bébé",
    prix: "12.00 TND",
    discount: "15.00 TND",
    image: "/cardImgs/Bepanthen.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Pommade protectrice pour le change du bébé, aide à prévenir les érythèmes fessiers.",
    category: "Bébé Maman",
    rating: 2.7, // bad review
    reviews: 6,
  },
  {
    id: 55,
    marque: "Nuk",
    nom: "Nuk Tétine Silicone Bébé",
    prix: "8.00 TND",
    discount: "10.00 TND",
    image: "/cardImgs/NukTétineSilicone.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Tétine en silicone pour bébés, adaptée à la bouche et aux dents des nourrissons.",
    category: "Bébé Maman",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 56,
    marque: "Pampers",
    nom: "Pampers Couches Bébé",
    prix: "30.00 TND",
    discount: "35.00 TND",
    image: "/cardImgs/PampersCouches.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Couches jetables pour bébés, ultra absorbantes pour un confort optimal.",
    category: "Bébé Maman",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 57,
    marque: "Lansinoh",
    nom: "Lansinoh Crème Soin Mamelons",
    prix: "18.00 TND",
    discount: "22.00 TND",
    image: "/cardImgs/LansinohCrème.jpg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Crème hydratante pour les mamelons, idéale pour les mères allaitantes.",
    category: "Bébé Maman",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 58,
    marque: "Weleda",
    nom: "Weleda Huile de Massage Bébé",
    prix: "25.00 TND",
    discount: "30.00 TND",
    image: "/cardImgs/WeledaHuile.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Huile de massage douce et apaisante pour bébé, à base d'ingrédients naturels.",
    category: "Bébé Maman",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 59,
    marque: "Biolane",
    nom: "Biolane Gel Lavant Doux",
    prix: "10.00 TND",
    discount: "12.00 TND",
    image: "/cardImgs/BiolaneGelLavant.jpg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Gel lavant doux pour le bain de bébé, respectueux de sa peau sensible.",
    category: "Bébé Maman",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 60,
    marque: "Chicco",
    nom: "Chicco Biberon Bébé",
    prix: "14.00 TND",
    discount: "18.00 TND",
    image: "/cardImgs/ChiccoBiberon.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Biberon en plastique avec tétine anti-coliques, idéal pour l'alimentation de bébé.",
    category: "Bébé Maman",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 61,
    marque: "Aptamil",
    nom: "Aptamil Lait 1er Age",
    prix: "50.00 TND",
    discount: "55.00 TND",
    image: "/cardImgs/AptamilLait.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Lait infantile adapté aux nourrissons, riche en nutriments essentiels.",
    category: "Bébé Maman",
    rating: 4.3,
    reviews: 30,
  },

  // Homeopathic

  {
    id: 62,
    marque: "Boiron",
    nom: "Oscillococcinum",
    prix: "30.00 TND",
    discount: "35.00 TND",
    image: "/cardImgs/Oscillococcinum.png",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Remède homéopathique contre les symptômes de la grippe, notamment la fièvre, la fatigue et les douleurs corporelles.",
    category: "Homeopathic",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 63,
    marque: "Weleda",
    nom: "Weleda Arnica Massage Oil",
    prix: "20.00 TND",
    discount: "25.00 TND",
    image: "/cardImgs/WeledaArnica.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Huile de massage homéopathique à base d'arnica pour soulager les douleurs musculaires et les tensions.",
    category: "Homeopathic",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 64,
    marque: "Heel",
    nom: "Traumeel S",
    prix: "18.00 TND",
    discount: "22.00 TND",
    image: "/cardImgs/Traumeel.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Médicament homéopathique pour traiter les douleurs et inflammations musculaires et articulaires.",
    category: "Homeopathic",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 65,
    marque: "Boiron",
    nom: "Camilia",
    prix: "10.00 TND",
    discount: "12.00 TND",
    image: "/cardImgs/Camilia.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Traitement homéopathique pour soulager les douleurs liées à la poussée dentaire chez les bébés.",
    category: "Homeopathic",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 66,
    marque: "Liddell",
    nom: "Liddell Stress Relief",
    prix: "28.00 TND",
    discount: "32.00 TND",
    image: "/cardImgs/LiddellStress.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Remède homéopathique pour réduire le stress et l'anxiété, sans effets secondaires.",
    category: "Homeopathic",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 67,
    marque: "Hyland's",
    nom: "Hyland's Calms Forte",
    prix: "22.00 TND",
    discount: "27.00 TND",
    image: "/cardImgs/Hyland'sCalms.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Remède homéopathique pour soulager les symptômes d'anxiété et d'insomnie.",
    category: "Homeopathic",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 68,
    marque: "Boiron",
    nom: "Arnica Montana",
    prix: "15.00 TND",
    discount: "18.00 TND",
    image: "/cardImgs/ArnicaMontana.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Traitement homéopathique pour soulager les douleurs musculaires, les contusions et les blessures légères.",
    category: "Homeopathic",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 69,
    marque: "Weleda",
    nom: "Weleda Calendula Cream",
    prix: "18.00 TND",
    discount: "22.00 TND",
    image: "/cardImgs/WeledaCalendula.jpg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Crème homéopathique pour soulager les irritations et apaiser la peau délicate des bébés et des adultes.",
    category: "Homeopathic",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 70,
    marque: "Schwabe",
    nom: "Bach Rescue Remedy",
    prix: "28.00 TND",
    discount: "35.00 TND",
    image: "/cardImgs/BachRescueRemedy.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Remède de fleurs de Bach pour gérer le stress et les émotions fortes, une solution naturelle pour l'anxiété.",
    category: "Homeopathic",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 71,
    marque: "Liddell",
    nom: "Liddell Sleep Aid",
    prix: "25.00 TND",
    discount: "30.00 TND",
    image: "/public/cardImgs/LiddellSleepAid.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Remède homéopathique pour favoriser le sommeil naturel et traiter l'insomnie sans effets secondaires.",
    category: "Homeopathic",
    rating: 4.3,
    reviews: 30,
    //Parapharmacie
    id: 72,
    marque: "Vichy",
    nom: "Vichy Mineral 89",
    prix: "45.00 TND",
    discount: "50.00 TND",
    image: "/cardImgs/VichyMineral89.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Sérum hydratant quotidien qui renforce la peau et protège contre les agressions extérieures.",
    category: "Parapharmacie",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 73,
    marque: "La Roche-Posay",
    nom: "La Roche-Posay Anthelios XL",
    prix: "40.00 TND",
    discount: "45.00 TND",
    image: "/cardImgs/LaRoche-PosayAntheliosXL.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Crème solaire à très haute protection pour les peaux sensibles, protège contre les rayons UVA et UVB.",
    category: "Parapharmacie",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 74,
    marque: "Avene",
    nom: "Avene Eau Thermale",
    prix: "20.00 TND",
    discount: "25.00 TND",
    image: "/cardImgs/AvèneEauThermaleSpray.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Spray d'eau thermale apaisante pour hydrater et rafraîchir la peau, idéal pour les peaux sensibles.",
    category: "Parapharmacie",
    rating: 2.6, // bad review
    reviews: 9,
  },
  {
    id: 75,
    marque: "Bioderma",
    nom: "Bioderma Sensibio H2O",
    prix: "30.00 TND",
    discount: "35.00 TND",
    image: "/cardImgs/BiodermaSensibioH2O.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Solution micellaire pour démaquiller et nettoyer en douceur les peaux sensibles.",
    category: "Parapharmacie",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 76,
    marque: "Mustela",
    nom: "Mustela Hydra Bébé",
    prix: "35.00 TND",
    discount: "40.00 TND",
    image: "/cardImgs/MustelaCrèmeHydratanteBébé.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Crème hydratante pour bébé, idéale pour la peau délicate des nourrissons et enfants.",
    category: "Parapharmacie",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 77,
    marque: "Eucerin",
    nom: "Eucerin AtopiControl",
    prix: "50.00 TND",
    discount: "55.00 TND",
    image: "/cardImgs/EucerinAtopiControl.jpg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Crème pour les peaux sujettes à l'eczéma et la sécheresse cutanée, soulage les démangeaisons.",
    category: "Parapharmacie",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 78,
    marque: "L'Occitane",
    nom: "L'Occitane Shea Butter Hand Cream",
    prix: "30.00 TND",
    discount: "35.00 TND",
    image: "/cardImgs/L'Occitane.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Crème pour les mains à base de beurre de karité, hydrate et nourrit en profondeur les mains sèches.",
    category: "Parapharmacie",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 79,
    marque: "Filorga",
    nom: "Filorga NCTF Reverse",
    prix: "120.00 TND",
    discount: "140.00 TND",
    image: "/cardImgs/Filorga.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Crème anti-âge qui lutte contre les signes de vieillissement et revitalise la peau en profondeur.",
    category: "Parapharmacie",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 80,
    marque: "Vichy",
    nom: "Vichy Normaderm",
    prix: "35.00 TND",
    discount: "40.00 TND",
    image: "/cardImgs/VichyNormaderm.jpg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Gel nettoyant pour les peaux mixtes à grasses, aide à éliminer les imperfections et matifier la peau.",
    category: "Parapharmacie",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 81,
    marque: "Clarins",
    nom: "Clarins Double Serum",
    prix: "200.00 TND",
    discount: "250.00 TND",
    image: "/cardImgs/ClarinsDoubleSerum.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Sérum anti-âge intensif qui redonne à la peau sa jeunesse et son éclat.",
    category: "Parapharmacie",
    rating: 4.3,
    reviews: 30,
  },

  // Bio Médecines naturelles
  {
    id: 82,
    marque: "Pranarom",
    nom: "Pranarom Huile Essentielle Lavande Vraie",
    prix: "25.00 TND",
    discount: "30.00 TND",
    image: "/cardImgs/PranaromHuileEssentielleLavandeVraie.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Huile essentielle de lavande vraie, utilisée pour ses propriétés relaxantes et apaisantes.",
    category: "Bio Médecines naturelles",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 83,
    marque: "Weleda",
    nom: "Weleda Arnica Gel",
    prix: "35.00 TND",
    discount: "40.00 TND",
    image: "/cardImgs/WeledaArnicaGel.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Gel à base d'arnica bio pour soulager les douleurs musculaires et les contusions.",
    category: "Bio Médecines naturelles",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 84,
    marque: "Herbion",
    nom: "Herbion Miel de Manuka",
    prix: "45.00 TND",
    discount: "50.00 TND",
    image: "/cardImgs/HerbionMiel.jpeg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Miel de Manuka bio reconnu pour ses propriétés antibactériennes et cicatrisantes.",
    category: "Bio Médecines naturelles",
    rating: 2.3, // bad review
    reviews: 5,
  },
  {
    id: 85,
    marque: "Naturactive",
    nom: "Naturactive Ginkgo Biloba",
    prix: "28.00 TND",
    discount: "33.00 TND",
    image: "/cardImgs/NaturactiveGinkgoBiloba.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Complément alimentaire à base de Ginkgo Biloba bio, favorise la circulation sanguine et améliore la mémoire.",
    category: "Bio Médecines naturelles",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 86,
    marque: "Santarome",
    nom: "Santarome Bio Détox",
    prix: "35.00 TND",
    discount: "40.00 TND",
    image: "/cardImgs/SantaromeBioD.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Infusion détox bio à base de plantes naturelles pour favoriser l'élimination des toxines.",
    category: "Bio Médecines naturelles",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 87,
    marque: "Phytosun",
    nom: "Phytosun Huile Essentielle Eucalyptus Radiata",
    prix: "20.00 TND",
    discount: "25.00 TND",
    image: "/cardImgs/PhytosunHuileEssentielleEucalyptusRadiata.jpg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Huile essentielle d'eucalyptus radiata bio pour dégager les voies respiratoires et stimuler l'immunité.",
    category: "Bio Médecines naturelles",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 88,
    marque: "Aromazone",
    nom: "Aromazone Huile Essentielle Tea Tree",
    prix: "15.00 TND",
    discount: "18.00 TND",
    image: "/cardImgs/AromazoneHuileEssentielleTeaTree.png",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Huile essentielle de Tea Tree bio, idéale pour ses propriétés antibactériennes et antiseptiques.",
    category: "Bio Médecines naturelles",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 89,
    marque: "Biofloral",
    nom: "Biofloral Tisane Bio Relax",
    prix: "18.00 TND",
    discount: "22.00 TND",
    image: "/cardImgs/BiofloralTisaneBioRelax.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Tisane relaxante bio à base de plantes apaisantes, idéale pour réduire le stress et favoriser la détente.",
    category: "Bio Médecines naturelles",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 90,
    marque: "Herbaflor",
    nom: "Herbaflor Huile Essentielle Romarin",
    prix: "22.00 TND",
    discount: "25.00 TND",
    image: "/cardImgs/HerbaflorHuileEssentielleRomarin.jpg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Huile essentielle de romarin bio, utilisée pour stimuler la circulation sanguine et soulager les douleurs musculaires.",
    category: "Bio Médecines naturelles",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 91,
    marque: "Florame",
    nom: "Florame Huile Essentielle Lavande Fine",
    prix: "30.00 TND",
    discount: "35.00 TND",
    image: "/cardImgs/FlorameHuileEssentielleLavandeFine.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Huile essentielle de lavande fine bio, idéale pour la relaxation et l'apaisement du stress.",
    category: "Bio Médecines naturelles",
    rating: 4.3,
    reviews: 30,
  },

  //Matériel médical
  {
    id: 92,
    marque: "Omron",
    nom: "Omron M6 Comfort Tensiomètre Automatique",
    prix: "180.00 TND",
    discount: "200.00 TND",
    image: "/cardImgs/OrthomolImmun.jpeg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Tensiomètre automatique avec technologie Intellisense pour une mesure précise de la pression artérielle.",
    category: "Matériel médical",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 93,
    marque: "Beurer",
    nom: "Beurer Inhalateur IH 40",
    prix: "220.00 TND",
    discount: "250.00 TND",
    image: "/cardImgs/BeurerInhalateur.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Inhalateur à vapeur pour les voies respiratoires, idéal pour le traitement des rhumes et des problèmes respiratoires.",
    category: "Matériel médical",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 94,
    marque: "Medisana",
    nom: "Medisana Thermomètre InfraRouge FTN",
    prix: "55.00 TND",
    discount: "60.00 TND",
    image: "/cardImgs/Medisana.jpg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Thermomètre à infrarouge pour des mesures rapides et sans contact de la température corporelle.",
    category: "Matériel médical",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 95,
    marque: "Philips",
    nom: "Philips Sonicare Brosse à dents électrique",
    prix: "130.00 TND",
    discount: "150.00 TND",
    image: "/cardImgs/Philips.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Brosse à dents électrique Sonicare, technologie sonique pour un nettoyage en profondeur.",
    category: "Matériel médical",
    rating: 4.3,
    reviews: 30,
  },
  {
    id: 96,
    marque: "Medtronic",
    nom: "Medtronic Insulin Pump MiniMed 630G",
    prix: "3000.00 TND",
    discount: "3500.00 TND",
    image: "/cardImgs/Medtronic.jpeg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Pompe à insuline MiniMed 630G pour une gestion optimale du diabète.",
    category: "Matériel médical",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 97,
    marque: "Withings",
    nom: "Withings Body+ Balance Connectée",
    prix: "200.00 TND",
    discount: "250.00 TND",
    image: "/cardImgs/WithingsBody.jpg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Balance connectée avec mesure du poids, de la graisse corporelle et de l'indice de masse corporelle (IMC).",
    category: "Matériel médical",
    rating: 2.0, // bad review
    reviews: 7,
  },
  {
    id: 98,
    marque: "Tenscare",
    nom: "Tenscare Machine TENS",
    prix: "90.00 TND",
    discount: "100.00 TND",
    image: "/cardImgs/Tenscare.jpeg",
    rupture: "En stock",
    Description:
      "Dispositif TENS pour soulager les douleurs musculaires et articulaires à domicile.",
    category: "Matériel médical",
    rating: 4.0,
    reviews: 20,
  },
  {
    id: 99,
    marque: "Fisher-Price",
    nom: "Fisher-Price Moniteur Bébé",
    prix: "150.00 TND",
    discount: "180.00 TND",
    image: "/cardImgs/Fisher-Price.jpg",
    nouveaux: "Top Vente",
    rupture: "En stock",
    Description:
      "Moniteur bébé audio et vidéo avec vision nocturne et portée longue distance.",
    category: "Matériel médical",
    rating: 4.5,
    reviews: 50,
  },
  {
    id: 100,
    marque: "Omron",
    nom: "Omron Nebuliseur MicroAir U22",
    prix: "170.00 TND",
    discount: "200.00 TND",
    image: "/cardImgs/OmronNebuliseur.jpg",
    nouveaux: "Nouveau",
    rupture: "En stock",
    Description:
      "Nébuliseur portable pour inhalation de médicaments, idéal pour les personnes souffrant de maladies respiratoires.",
    category: "Matériel médical",
    rating: 4.0,
    reviews: 10,
  },
  {
    id: 101,
    marque: "Salter",
    nom: "Salter Pèse-personne Digital",
    prix: "50.00 TND",
    discount: "60.00 TND",
    image: "/cardImgs/Salter.jpg",
    nouveaux: "Recommandé",
    rupture: "En stock",
    Description:
      "Pèse-personne numérique avec grande capacité et affichage facile à lire.",
    category: "Matériel médical",
    rating: 4.3,
    reviews: 30,
  },
];
